### ISSUE TITLE
SSH timed out 

### ISSUE THREAD

**Issue by dfrogy** [Universal-Rom-Tools/Universal-XML-Scraper#190]
when start to scraper it get SSH timed out  error and don't shut down emu station and start scraping.

**Comment by Universal-Rom-Tools** [comment]
arg .. that's bad...

Can you try to kill es directly with the SSH menu ?
Can you try to put your PI Ip in the SSH configuration ?
Can you check your root/password in SSH configuration ?
Are you sur you can acces in SSH to your PI ?

**Comment by dfrogy** [comment]
i checked all of it all ok. it scrapes it dont turn off emu-station put it in the down load file

**Comment by dfrogy** [comment]
https://www.youtube.com/watch?v=5zCYED2SYvs&t=2s

**Comment by Universal-Rom-Tools** [comment]
Can you open a CMD (start/execute : **cmd**)

go to the UXS dir (**cd x:\\....\\uxs\\ressources\\** )

and try this command : 

**plink.exe RETROPIE -ssh -l pi -pw raspberry killall emulationstation**

It's what UXS do...

You can see the error message (if any)

**Comment by Chogin** [comment]
Have the exact same problem since version 2.2 came out.

Only option is to shutdown Emulationstation manually.

**Comment by Universal-Rom-Tools** [comment]
I haven't touch the SSH option in the 2.2 :(
Can you try the process just up your post ?

**Comment by Chogin** [comment]
With the process above on the command prompt it works.

But it does not work using Universal XMP software.

Any idea on how to get this sorted. It is a pain to keep doing it manually. Reboot also doesn't work via Universal XML.

**Comment by Universal-Rom-Tools** [comment]
I will make some test tonight (but I haven't retropie :S) 

Will add some log too...

**Comment by jsianes** [comment]
I had the same issue yesterday and was forced to kill manually Emulationstation to avoid XML file rewrite when restarting.

**Comment by Universal-Rom-Tools** [comment]
Corrected in the last version

**Comment by orochikun** [comment]
Still fails to kill emulationstation from the app tho 

Retropie 4.2 
SSH enabled 
Autokill fails
