### ISSUE TITLE
Major loss of data on screenscraper.fr

### ISSUE THREAD

**Issue by IceLancerSR** [Universal-Rom-Tools/Universal-XML-Scraper#288]
Hey, sorry guys i cannot find my bearings on screenscraper.fr forums. Google Chrome login button doesnt even work, translate is impossible , using Firefox instead.
Anyway i have noticed Major loss of data on screenscraper.fr
Here is small example of scraped xml data 1 month ago and now

https://i.imgur.com/INJC9Z0.jpg
here is more
https://i.imgur.com/xrSFDpP.jpg
entire database suffered major loss, like 70% of data is missing

Left is NEW scraped data , as u can notice its almost Empty!
Right is old scrape And its very filled.
This is PSP in question , but same happened to NDS and some other platforms. I was wondering what happened and what might be the issue for such loss of data

Almost all `<desc>` and `<date>` are lost even `<genre>` has suffered losses.

-------
**PSP:**
Another problem A lot of games got broken date?
	Line 28: 	<releasedate>01010101T000000</releasedate>
	Line 87: 	<releasedate>01010101T000000</releasedate>
	Line 103: 	<releasedate>01010101T000000</releasedate>
	Line 133: 	<releasedate>01010101T000000</releasedate>
	Line 166: 	<releasedate>01010101T000000</releasedate>
	Line 212: 	<releasedate>01010101T000000</releasedate>
	Line 227: 	<releasedate>01010101T000000</releasedate>
	Line 243: 	<releasedate>01010101T000000</releasedate>
	Line 259: 	<releasedate>01010101T000000</releasedate>
	Line 289: 	<releasedate>01010101T000000</releasedate>
	Line 319: 	<releasedate>01010101T000000</releasedate>
	Line 367: 	<releasedate>01010101T000000</releasedate>
	Line 383: 	<releasedate>01010101T000000</releasedate>
	Line 429: 	<releasedate>01010101T000000</releasedate>
	Line 445: 	<releasedate>01010101T000000</releasedate>
	Line 635: 	<releasedate>01010101T000000</releasedate>
	Line 651: 	<releasedate>01010101T000000</releasedate>
	Line 667: 	<releasedate>01010101T000000</releasedate>
	Line 12: 	<releasedate>01010101T000000</releasedate>
	Line 12: 	<releasedate>01010101T000000</releasedate>
	Line 235: 	<releasedate>01010101T000000</releasedate>
	Line 235: 	<releasedate>01010101T000000</releasedate>
	Line 251: 	<releasedate>01010101T000000</releasedate>
	Line 251: 	<releasedate>01010101T000000</releasedate>
	Line 303: 	<releasedate>01010101T000000</releasedate>
	Line 303: 	<releasedate>01010101T000000</releasedate>
	Line 711: 	<releasedate>01010101T000000</releasedate>
	Line 711: 	<releasedate>01010101T000000</releasedate>

-----------------------------------------
**snes:**
(1433 hits in 1 file)
	Line 1064: 	<releasedate>01010101T000000</releasedate>
	Line 1064: 	<releasedate>01010101T000000</releasedate>
	Line 1080: 	<releasedate>01010101T000000</releasedate>
	Line 1080: 	<releasedate>01010101T000000</releasedate>
	Line 1096: 	<releasedate>01010101T000000</releasedate>
for real? :(

P.S
Yes, I am using an account.

**Comment by IceLancerSR** [comment]
Here is more broken stuff compared to month ago..
Search "19910101T000000" (13 hits in 1 file)
SNES `<Date>`
Search "19910901T000000" (8 hits in 1 file)

Search "19930101T000000" (9 hits in 1 file)
Data scraped is a major mess

**Comment by Universal-Rom-Tools** [comment]
I talk about it at our DB manager ;) something happen this morning about "country" and was fixed... Can you re-test and told me if it's ok now ?

**Comment by IceLancerSR** [comment]
I did this scrape hfl hour before posting so it was 3 hours ago.
I will try again tho

**Comment by IceLancerSR** [comment]
Ok description is back
but some dates are still broken 
snes
Search "01010101T000000" (63 hits in 1 file)
psp (40 games)
"01010101T000000" (18 hits in 1 file)

**Comment by IceLancerSR** [comment]
![date](https://user-images.githubusercontent.com/4452102/34783891-0b03e252-f62d-11e7-8ece-718113e340e2.jpg)
Yeah dates are broken.

**Comment by Universal-Rom-Tools** [comment]
Ok, I just check some info.

1/For the date problem, it seems to be "work as intended" : 
https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/blob/master/Scraper.au3#L213

When no date found (data missing on the DB or no match found on the country), it put "01010101T000000" as "releasedate" is it a problem in Emulationstation ?
(Never had issue on that :S )

If it's a real problem I need to change that.

2/ for the double "image" tag closed, is a known issue. I need to work on that :(

3/ for the Empty "game" I think you check in the general config "Add missing roms in XML" so it's normal. The game wasn't found but UXS put an empty entry in gamelist.xml. (I can tell that because there is no game ID in the exemple you give)

Thank you for your return ;)

**Comment by IceLancerSR** [comment]
For date, yes its problem , if it doesnt find data, write no data, dont write fake date

For empty game , i already have write missing toms to xml
and it did wrote the game but it didnt write its name it just wrote path

**Comment by Universal-Rom-Tools** [comment]
Ok, I will see for the date problem when I can ;)

What "Add missing roms in XML" did is exactly that.
UXS don't found the game, so he don't know the "name" of the game.
It just put an empty entry with all tag and only the path filled.

The fact some game have ' in the filename is "an other problem" ;)
And normally not a "big" problem...
The roms file you have aren't referenced with their Hash in the DB (I think)

Exemple : 
**Donkey Kong Country - Blockbuster World Video Game Championship II (USA)**
Is not in the referenced file comonly scraped and associated to this game (and haven't  ' in the name) : 
https://www.screenscraper.fr/gameinfos.php?gameid=2149&action=onglet&zone=gameinfosroms

For memories : 

When you scrape a game in "CRC+Filename" mode, UXS Hash the file and try to found a matching Hash in the DB. If he can't he try to find a romfile with the same name (exactly but without extension)
And it's in this case some ' can be a problem... 

Try to catch an other rom like a rom from a "No Intro" Romset and try again ;) you will see it work ;)
Or if you don't want to DL an other rom try to rename it with a referenced one (in this exemple : "Donkey Kong Country (USA).zip" will be fine ;) )

**Comment by IceLancerSR** [comment]
When i am doing xml to attract romlist with py i just append ,/ and extension and write rest of path to name.
That way i can actually see game name in frontend
`path = re.sub("\.[^.]*$", "", path)`

**Comment by Universal-Rom-Tools** [comment]
Not sure, but I think you can do that with UXS in 2 Time : 

First Scrape without  "Add missing roms in XML"  and all the option you need.

Then select in option name as Filename without Extension
And in General configuration check  "Add missing roms in XML" and Scrape in "Update" Mode.

UXS will add only the missing one and put filename without extension as name ;)

**Comment by IceLancerSR** [comment]
Look here:
sselph scraper ur web site

`	<game id="2478" source="screenscraper.fr">
		<path>./Beavis and Butt-Head (USA).zip</path>
		<name>Beavis and Butt-Head (USA)</name>
		<desc>Beavis and Butthead are on the couch watching television. While flipping through the channels they come across an ad for a GWAR concert. Now they want to go to the GWAR concert, but they have no money for concert tickets. So in their infallible logic, they think that if they take pictures of themselves doing cool things, they will be able to get into the concert for free.

The game contains four main levels which are Highland High School, Streets of Highland, Highland Hospital and the Turbo Mall 2000 and the final level at the concert.</desc>
		<image>./boxart/Beavis and Butt-Head (USA).png</image>
		<rating>0.55</rating>
		<releasedate>19941101T000000</releasedate>
		<developer>Realtime Associates</developer>
		<publisher>Viacom</publisher>
		<genre>Platform</genre>
		<players>2</players>
		<marquee>./wheel/Beavis and Butt-Head (USA).png</marquee>
		<video>./snap/Beavis and Butt-Head (USA).mp4</video>
		<wheel>./wheel/Beavis and Butt-Head (USA).png</wheel>
	</game>`
XML scraper data for same game your site
`	<game id="" source="ScreenScraper">
		<path>/home/pi/RetroPie/roms/Super Nintendo Entertainment System/MTV's Beavis and Butt-Head (USA).zip</path>
		<name/>
		<desc/>
		<image/>
		<image/>
		<marquee/>
		<video/>
		<thumbnail/>
		<rating></rating>
		<releasedate></releasedate>
		<developer/>
		<publisher/>
		<genre/>
		<players/>
	</game>`

**Comment by IceLancerSR** [comment]
Meh i give up.
I will just go to hyperspin. I am getting massivly broken data all over. And incosistent scrap. One scrape i get info ,other scrape i dont. Or it gets broken with no data
